### ISSUE TITLE
conflicting return type

### ISSUE THREAD

**Issue by leatherbacks** [gshau/SQM_TSL2591#1]
Trying the SQM example gives the following error when compiling.  "SQM_TSL2591.h:157: error: conflicting return type specified for 'virtual void SQM_TSL2591::getEvent(sensors_event_t*)'
   void getEvent  ( sensors_event_t* );"

Any ideas on how to resolve?

**Comment by gshau** [comment]
@leatherbacks What are you using to compile the source?  Any further details might help with diagnosing the problem.

**Comment by leatherbacks** [comment]
I am using the Arduino IDE (version 1.8.5) 

Here is the complete error message:

In file included from C:\Arduino\sketch_feb11b\sketch_feb11b.ino:12:0:

C:\Arduino\libraries\SQM_TSL2591/SQM_TSL2591.h:166:8: error: conflicting return type specified for 'virtual void SQM_TSL2591::getEvent(sensors_event_t*)'

   void getEvent  ( sensors_event_t* );

        ^

In file included from C:\Arduino\sketch_feb11b\sketch_feb11b.ino:11:0:

C:\Arduino\libraries\Adafruit_Unified_Sensor/Adafruit_Sensor.h:147:16: error:   overriding 'virtual bool Adafruit_Sensor::getEvent(sensors_event_t*)'

   virtual bool getEvent(sensors_event_t*) = 0;

                ^

exit status 1
Error compiling for board

**Comment by gshau** [comment]
Updated to work with recent Adafruit_Sensor update.  Please check and let me know if that doesn't work.  Otherwise, I'm closing this issue.
